### ISSUE TITLE
Mod totally broken as of patch 9.1.5

### ISSUE THREAD

**Issue by Loredrin** [Torhal/Broker_Currency#16]
Any chance at a fix for this mod? Or is it abandoned?

**Comment by TreizeEU** [comment]
This addon hasn't been updated by Torhal since version 9.0.5.7 back in April, and he doesn't appear to let us know how the rework of it was going.

For now, I've used version 9.0.2.1 and manually added missing currencies myself to the "Currencies.lua" file.

Attaching my current version of above mentioned file.
[Currencies.zip](https://github.com/Torhal/Broker_Currency/files/7697487/Currencies.zip)

**Comment by TreizeEU** [comment]
Attaching my current version of above mentioned file (includin patch 9.2 PvE currencies).

[Currencies.zip](https://github.com/Torhal/Broker_Currency/files/8128274/Currencies.zip)

**Comment by TreizeEU** [comment]
Uploading my currently working version of Broker_Currency, with added currencies that I think will be used in Dragonflight (including Primeval Essence, used in this pre-patch event).

@Torhal 
For future reference, all I've done to this old version (9.0.2.1) of the file Broker_Currency.lua, is to comment out the following lines: 761-765, since this week's pre-patch version broke it and I don't know a better way to fix it.

[Broker_Currency.zip](https://github.com/Torhal/Broker_Currency/files/10049173/Broker_Currency.zip)

**Comment by houseofmabel** [comment]
> Uploading my currently working version of Broker_Currency, with added currencies that I think will be used in Dragonflight (including Primeval Essence, used in this pre-patch event).

Thanks so much for this!

However, I think it uses the old format pet charm, which has now been split into two:

	POLISHED_PET_CHARM = 163036,
	SHINY_PET_CHARM = 116415,
	
Obvs. these then have to be added in to ITEM_CURRENCY_IDS

Hope this helps!

**Comment by TreizeEU** [comment]
Good find, I fixed it in the below folder.

However I still have no idea why some item-currencies are in full caps ingame (just as they're written in the files), but they seems to work. Polished pet charm is one of them, but does appear to work.

[Broker_Currency.zip](https://github.com/Torhal/Broker_Currency/files/11864281/Broker_Currency.zip)

**Comment by blindseerjb** [comment]
Good afternoon,
I installed version 9.0.2.1 and then unzipped the folder supplied by @TreizeEU however all I get from the data text is "Initializing".

**Comment by TreizeEU** [comment]
@blindseerjb 
Did you only download the zip folder I uploaded here, and unzipped where addons goes? I wonder if files from another version remains or weren't replaced as it should?

**Comment by blindseerjb** [comment]
@TreizeEU I first installed 9.0.2.1 and then unzipped your folder into my addons folder. Do I still need 9.0.2.1 with your folder??

**Comment by TreizeEU** [comment]
My zipped folder should be the entire thing?

**Comment by blindseerjb** [comment]
@TreizeEU I got it to work. I deleted the folder from 9.0.2.1 and unzipped your folder into a new Broker_Currency folder and it now appears to be working. Thank you!!

**Comment by TreizeEU** [comment]
You're quite welcome. :)
