### ISSUE TITLE
9.0.5.7 None of the information other than gold shows up in summary

### ISSUE THREAD

**Issue by BigFire321** [Torhal/Broker_Currency#8]
Version 9.0.5.7.  I've selected Shadowland currency I want to display in the summary page.  None of them show up except for gold/money.   Also, after the first character, the rest of my characters cannot load the mod.

**Comment by Wraithlord2015** [comment]
Just wanted to post an update. Under the pull requests - christophknuth posted a fix that allows the latest version of the addon to be used. I'm currently using it and haven't had any errors thus far.

**Comment by BigFire321** [comment]
I'm still only getting gold as display, albeit the alts not showing up is resolved.  I'm using TitanPanel to dock the broker_currency.

**Comment by Wraithlord2015** [comment]
Initially when I posted - it wasn't exhibiting that behavior. When I logged back in just a few minutes ago - no currencies are showing in the mouseover summary list (as stated above). Label me annoyed - I thought it was finally fixed.

**Comment by iWolf1** [comment]
I tracked the display issue to OptionIcons and BrokerIcons being declared and used but never initialized in tooltip.lua

Broker_Currency.lua has the same variables populated so I made them members of the Broker_Currency object and use those to initialize the ones in tooltip.lua that made most of the currencies show except for the money (gold, silver, & copper)

Add this 2 lines right before the last "end" in Broker_Currency.lua

`    Broker_Currency.OptionIcons = OptionIcons`
`    Broker_Currency.BrokerIcons = BrokerIcons`

and change lines 45 & 46 of tooltip.lua from:
`    local OptionIcons = {}`
`    local BrokerIcons = {}`
to:
`    local OptionIcons = Broker_Currency.OptionIcons`
`    local BrokerIcons = Broker_Currency.BrokerIcons`

As it turns out something is zeroing out the character's money specifically on logout, as it is correctly saved on /reload and I haven't been able to figure out when or why it is happening

**Comment by BigFire321** [comment]
OK that kinda fix the problem.  Right now, with that fix, everytime I login a character, the character's currently gold amount is added to the daily total.
